// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecyoojcymtpwpjthnthj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeW9vamN5bXRwd3BqdGhudGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDAyODgsImV4cCI6MjA3MjMxNjI4OH0.Udf-fBHdIozQeWouK7kERhheqTCqTXBsvlf0VlYAzD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});